//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MailService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mail
    {
        public int MailId { get; set; }
        public Nullable<System.DateTime> MailDate { get; set; }
        public string FromEmail { get; set; }
        public string ToEmail { get; set; }
        public string Subject { get; set; }
        public string Message { get; set; }
        public Nullable<bool> IsAttachmentPresent { get; set; }
        public string EmailStatus { get; set; }
        public string MailFolder { get; set; }
        public Nullable<bool> IsRead { get; set; }
    }
}
